### ISSUE TITLE
Verbose

### ISSUE THREAD

**Issue by johnwojo** [learn-co-curriculum/js-principles-scope-chain-readme#2]
Hey there! I found this lesson to be particularly confusing. It almost seemed intentional. Scope seems a little bit easier to define... with far fewer words.

"All variables and functions declared in outer scopes are available in inner scopes via the scope chain."

The first seven or eight paragraphs seem like they could be summed up in just this one sentence above, which is found half way down the page. I also typically disable GIFs when trying to deep dive into reading this intellectually challenging. While it may not be for everyone, those with ADHD (like myself) can find it difficult to wade through this sort of lesson, especially with flashing notifications and GIFs.

I appreciate your consideration on this issue! Your team has done a fantastic job.

**Comment by cjbrock** [comment]
Hey @johnwojo! You are absolutely correct. We are currently working on rewriting our JavaScript section and this lesson is on the shortlist of ones to be redone. It's a bit of an older style for us and s you can see, it's less concise and it just doesn't do a great job of getting the point across without a lot of useless information and unnecessary distraction. Thank you for taking your time to let us know a bit more about how you learn - it's really helpful for us as a curriculum team to have more information about how students go through the program (especially turning off GIFs, I personally do that too but we debate it a lot!). You're doing a great job too. Thanks for being a part of our community. 
// <3 Corinna
