### ISSUE TITLE
 Contradictory Statements Between Lessons 

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/js-principles-scope-chain-readme#5]
**LESSON: INTRO TO JAVASCRIPT**
Identify JavaScript Syntax and Best Practices
Using Semicolons
In JavaScript, ending each statement with a semicolon is optional. When you run some JavaScript code in the browser, the **JavaScript engine actually makes multiple passes over the same code.** The **first pass is to parse the syntax of your code.** The **second pass is to initialize variables and functions** and store them in memory. And **the third pass is to actually execute the code line-by-line.** We'll learn more about the second and third phases in an upcoming lesson.

**LESSON: SCOPE CHAIN**
The JavaScript engine
When our JavaScript code is run in the browser, the **JavaScript engine actually makes two separate passes over our code:**

Compilation phase
**The first pass is the compilation phase**, in which the engine steps through our code line-by-line:
Execution phase
**The second pass is the execution phase.**

**Comment by sgharms** [comment]
We've added some nuance here to bring these two in harmony. Thanks for your fastidious identification of the two points of disagreement!

Steven
